# Generated by Django 4.2 on 2023-06-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_post_pic"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="pic", new_name="pict",),
    ]
