# Generated by Django 4.2 on 2023-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0007_remove_post_pict_post_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
